[build]
  command = "npm run build"
  publish = "/path/to/build"
  environment = { REACT_APP_API_LINK = "https://imdb-clone-6grh.onrender.com" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
